---
- name: Create folder
  file:
    path: "{{ project_path }}"
    state: directory
    mode: "0755"

- name: Create docker-compose yaml
  copy:
    dest: "{{ project_path}}/docker-compose.yaml"
    content: |
      version: '3.8'

      services:
        node_exporter:
          image: quay.io/prometheus/node-exporter:latest
          container_name: node_exporter
          command:
            - '--path.rootfs=/host'
          network_mode: host
          pid: host
          restart: unless-stopped
          volumes:
            - '/:/host:ro,rslave'

- name: start node_exporter container
  command:
    cmd: docker compose up -d
    chdir: "{{ project_path }}"

- name: Ensure node_exporter is running
  command: docker ps --filter "name=node_exporter"
  register: node_exporter_status
  changed_when: false